/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    Content: typeof import('./src/components/Content.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
  }
}
